### ISSUE TITLE
Simplify the Discharge View by Converting it to a Serializer

### ISSUE THREAD

**Issue by cp-Coder** [coronasafe/care#1205]
# Feature Request

## Is your feature request related to a problem? Please describe

- The discharge view has become complicated, making it difficult to understand and manage.

## Describe the solution you'd like

- To simplify the discharge view and improve its functionality, it is suggested that the view be converted to a serializer. A serializer can effectively handle complex data structures and relationships, making the view more organized and user-friendly.

## Describe alternatives you've considered

No alternative solutions were considered.

## Additional context

_This feature request was originally posted by user @vigneshhari in https://github.com/coronasafe/care/issues/1155#issuecomment-1381427807_

> Can you create another issue to move the discharge view to use a serializer? it was a rather simple view, now that it's complicated, I recommend using a serializer.

**Comment by nihal467** [comment]
@cp-Coder 

https://github.com/coronasafe/care_fe/issues/5271
https://github.com/coronasafe/care_fe/issues/5272

I am unassigning you from this backend issue since there are two issues you have already assigned last week in the care_fe and haven't pushed the fix yet. Once you push the fix for an already assigned issue, assign yourself new ones

**Comment by sainak** [comment]
closed by #1252
