### ISSUE TITLE
Centralise Linting across the project

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#1255]
Currently, the linting for Care is all over the place, PR's with a single line change end up making 100+ diffs,  
Create a PR that fixes all linting issues WRT the current linter config
Ensure linting pipelines fail when the project code is not in the right format.

**Comment by nihal467** [comment]
@cp-Coder 

https://github.com/coronasafe/care_fe/issues/5271
https://github.com/coronasafe/care_fe/issues/5272

I am unassigning you from this backend issue since there are two issues you have already assigned last week in the care_fe and haven't pushed the fix yet. Once you push the fix for an already assigned issue, assign yourself new ones
