### ISSUE TITLE
Flush Redis before loading static data

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2249]
Remove the existing keys of care_static_data before proceeding with the loading of static data in redis

**Comment by kushalbhana** [comment]
Can you tell me where could I locate this issue?

**Comment by rithviknishad** [comment]
@kushalbhana 

- https://github.com/coronasafe/care/blob/develop/care/facility/tasks/redis_index.py
- https://github.com/coronasafe/care/blob/develop/care/facility/management/commands/load_redis_index.py

cc: @sainak

**Comment by BlessedRice2004** [comment]
Hello @sainak, may I work on this issue?

**Comment by BlessedRice2004** [comment]
Thanks for assigning me. I'll look into it the moment I get off work!

**Comment by ghost** [comment]
Hey @JohnLu2004 If you don't have time for this , can I try out ?

**Comment by BlessedRice2004** [comment]
> Hey [@JohnLu2004](https://github.com/JohnLu2004) If you don't have time for this , can I try out ?

Thanks for the looking out for me, but I'm working on it. In terms of cpu usage and speed, it takes a while for processes to run in the dev container as opposed to outside of it. I'm working on it locally on my fork 😁

**Comment by BlessedRice2004** [comment]
I assume the keys that I need to delete only get created when/after the app has been used for some time? 
- After ``make up``, there don't seem to be any keys. I found that we had 0 keys by making a python program that takes all the keys. 
- I also used the redis-cli and got back an empty array.

With this info, I assume that you'd like me to instead update the app so that every single time we try to load static data from redis, I delete the keys that have "care_static_data" as a prefix?
