### ISSUE TITLE
Fix Unit Tests

### ISSUE THREAD

**Issue by vigneshhari** [coronasafe/care#488]
All Unit Tests are broken, we need better unit testing with more edge cases on core functionality including permission scoping tests.

**Comment by millefalcon** [comment]
Hello, i would like to try this out. Any pointers on where i should get started ?

**Comment by vigneshhari** [comment]
Hi, we have a lot of breaking unit tests, you can start with those, and then later on we can write more unit tests and check more edge cases.

**Comment by millefalcon** [comment]
Sure. I am bit confused about where these users and facilities are created. Or are they created using some sample data. Is there any get started guide i could look at ? This is what i see, after i have run the dev server.

![care](https://user-images.githubusercontent.com/16983964/95074995-737c5800-06dd-11eb-94b3-7e3f44d012a9.png)

**Comment by vigneshhari** [comment]
You can send an email at vichuhari100@gmail.com and we can schedule a call to explain the code a bit.

**Comment by millefalcon** [comment]
Sure. Thanks :)

**Comment by millefalcon** [comment]
So, i started going through some tests, and for one of the test for ex: `care.facility.tests.test_patient_sample_api.TestPatientSampleApi`, i found that the `facility` is not bound with the `patient` hence the `patient`s `failcity` attribute become `None` and it fails the test with `AttributeError: 'NoneType' object has no attribute 'external_id'`.

```python
...
 def get_sample_data(self, **kwargs):
        patient = kwargs.get("patient", self.patient)
        consultation = kwargs.get("consultation", self.consultation)
        return {
            "patient": str(patient.external_id),
            "consultation": str(consultation.external_id),
            "sample_type": "BA/ETA",
            "testing_facility": str(patient.facility.external_id),
        }
...
```

Should that been ` "testing_facility": str(consulation.facility.external_id),` instead of ` "testing_facility": str(patient.facility.external_id),`. I think, i need to read through once more :)


And some other tests are failing, because the `dict` from the `response` are not same as the `dict` expected, because some of the expected `dict` have 

Ex: `care.facility.tests.test_facility_api.TestFacility`
```python
...
 def test_active_facility_retrieval(self):
        """Test facility attributes can be retrieved"""
        facility = self.facility
        facility.created_by = self.user
        facility.save()
        response = self.client.get(self.get_url(str(facility.external_id)), format="json", redirect="follow")
        self.assertDictEqual(
            response.data,
            {**self.get_list_representation(facility), "modified_date": mock_equal, "created_date": mock_equal,},
        )
...
```

The `mock_equal` seems to be an instance of
```python
class EverythingEquals:
    def __eq__(self, other):
        return True
```
So it will get the `repr` of that object, and the assertion will fail anyway.

How should one handle this ? Any thoughts ?

**Comment by sainAk** [comment]
Closing in favour of #794
