### ISSUE TITLE
Facility Filter for GET Users API

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care#785]
- [ ] Add a facilities filter for GET Users API.
- [ ] Create Issue in care_fe for building the filters in the UI
- [ ] Create Issue in care_fe for creating link from Facility Home to /users?facility_id=xxxx

**Comment by vigneshhari** [comment]
We have another endpoint specifically for this already made.

**Comment by siddnikh** [comment]
@gigincg there's one for districts. I'm working on adding the facilities filter to the GET users API.

**Comment by vigneshhari** [comment]
@gigincg we had a separate API for this because of the way we store this data internally. The facility user relation is a many-to-many type relation, we can bring in facility filters here but it would not be computationally inefficient. if there is a strong use case for this API, we can start thinking about implementation.
